name: airport_navigator
description: A cross-platform airport navigation and flight info app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_svg: ^2.0.7
  geolocator: ^10.1.0
  http: ^1.2.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.0
  hive: ^4.0.0
  hive_flutter: ^2.0.0
  provider: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/maps/
